### ISSUE TITLE
Error during Running Evaluation Script

### ISSUE THREAD

**Issue by sayanmandal** [jiasenlu/visDial.pytorch#8]
I am getting the following error after executing eval.py. I am using python2.7
14CS30032@cpusrv-gpu-112:~/visDial.pytorch$ python2.7 eval/eval_G_DIS.py --data_dir model/ --model_path model/save/HCIAE-G-DIS.pth --cuda
/usr/lib64/python2.7/site-packages/h5py/__init__.py:13: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
  from h5py import _conv
/usr/lib64/python2.7/site-packages/h5py/__init__.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
  from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/usr/lib64/python2.7/site-packages/h5py/_hl/group.py:15: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
  from h5py import h5g, h5i, h5o, h5r, h5t, h5l, h5p
Traceback (most recent call last):
  File "eval/eval_G_DIS.py", line 30, in <module>
    from misc.netG import _netG
  File "/home/du4/14CS30032/visDial.pytorch/misc/netG.py", line 147
    if self.mos_flag:
    ^
IndentationError: unexpected indent

**Comment by sayanmandal** [comment]
Now I am getting this error, 
Traceback (most recent call last):
  File "eval/eval_G_DIS.py", line 98, in <module>
    netG = _netG(opt.model, n_words, opt.ninp, opt.nhid, opt.nlayers, opt.dropout)
  File "/home/du4/14CS30032/visDial.pytorch/misc/netG.py", line 20, in __init__
    self.mos_layer = mixture_of_softmaxes(nhid, 5, ntoken + 1)
NameError: global name 'mixture_of_softmaxes' is not defined
I checked in the netG.py and indeed there was no functions defined with name 'mixture_of_softmaxes'

**Comment by sayanmandal** [comment]
can't run eval.py due to the following error.
 self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for _netG:
	Missing key(s) in state_dict: "mos_layer.prior.weight", "mos_layer.latent.0.bias", "mos_layer.latent.0.weight", "mos_layer.decoder.bias", "mos_layer.decoder.weight"
